from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from hf_agent.manifest import read_simple_manifest


VALID_STAGES = {"manifest", "seo", "quality", "all", "comment"}


def report_id_for_manifest(manifest: dict[str, str], fallback: str) -> str:
    pr_url = manifest.get("translation.pr_url", "")
    if "/pull/" in pr_url:
        return f"pr-{pr_url.rstrip('/').split('/')[-1]}"
    run_id = manifest.get("run.id")
    if run_id:
        return run_id
    return Path(fallback).stem


def run(cmd: list[str], cwd: Path) -> None:
    print("+", " ".join(cmd), flush=True)
    subprocess.run(cmd, cwd=cwd, check=True)


def write_request(report_dir: Path, manifest: dict[str, str]) -> None:
    request = "\n".join(
        [
            "# Review Request",
            "",
            f"- Target repo: {manifest.get('translation.target_repo', '')}",
            f"- Branch: {manifest.get('translation.branch', '')}",
            f"- File path: {manifest.get('translation.file_path', '')}",
            f"- PR URL: {manifest.get('translation.pr_url', '')}",
            "",
            "SEO and quality reports were generated by the hf agent workflow runner.",
            "",
        ]
    )
    (report_dir / "request.md").write_text(request)


def main() -> int:
    parser = argparse.ArgumentParser(description="Run SEO and quality skills from a translation manifest.")
    parser.add_argument("--manifest", required=True)
    parser.add_argument("--target-root", required=True)
    parser.add_argument("--reports-root", default="reports")
    parser.add_argument("--stage", choices=sorted(VALID_STAGES), default="all")
    parser.add_argument("--run-json", default="", help="Optional path for machine-readable run state.")
    args = parser.parse_args()

    repo_root = Path(__file__).resolve().parents[2]
    manifest_path = Path(args.manifest).resolve()
    target_root = Path(args.target_root).resolve()
    reports_root = (repo_root / args.reports_root).resolve()
    manifest = read_simple_manifest(manifest_path)
    report_id = report_id_for_manifest(manifest, manifest_path.name)
    report_dir = reports_root / report_id
    report_dir.mkdir(parents=True, exist_ok=True)

    manifest_copy = report_dir / "manifest.yaml"
    if manifest_path != manifest_copy:
        shutil.copyfile(manifest_path, manifest_copy)
    write_request(report_dir, manifest)

    reports: dict[str, str] = {}
    if args.stage in {"seo", "all"}:
        output = report_dir / "seo-report.md"
        run(
            [
                "python3",
                "skills/seo/tools/simple_seo_report.py",
                "--manifest",
                str(manifest_copy),
                "--target-root",
                str(target_root),
                "--output",
                str(output),
            ],
            cwd=repo_root,
        )
        reports["seo"] = str(output)

    if args.stage in {"quality", "all"}:
        output = report_dir / "quality-report.md"
        run(
            [
                "python3",
                "skills/quality/tools/simple_quality_report.py",
                "--manifest",
                str(manifest_copy),
                "--target-root",
                str(target_root),
                "--output",
                str(output),
            ],
            cwd=repo_root,
        )
        reports["quality"] = str(output)

    state = {
        "lifecycle": "finished",
        "stage": args.stage,
        "target_repo": manifest.get("translation.target_repo", ""),
        "pr_url": manifest.get("translation.pr_url", ""),
        "translation_file": manifest.get("translation.file_path", ""),
        "report_dir": str(report_dir),
        "manifest": str(manifest_copy),
        "reports": reports,
        "created_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
    }
    run_json = Path(args.run_json) if args.run_json else report_dir / "run.json"
    run_json.parent.mkdir(parents=True, exist_ok=True)
    run_json.write_text(json.dumps(state, indent=2, sort_keys=True) + "\n")
    print(f"Wrote run state: {run_json}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
